package gui;

import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alexgray
 */
public class GUIForm extends javax.swing.JFrame
{

    Renderer renderer;
    Thread openGLInstance;
    /**
     * Creates new form NewJFrame
     */
    public GUIForm()
    {
        initComponents();
        renderer = new Renderer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        topSeperator = new javax.swing.JSeparator();
        gaMenuPanel = new javax.swing.JPanel();
        startGaButton = new javax.swing.JButton();
        stopGaButton = new javax.swing.JButton();
        resetGaButton = new javax.swing.JButton();
        generationsSlider = new javax.swing.JSlider();
        generationsLabel = new javax.swing.JLabel();
        populationLabel = new javax.swing.JLabel();
        populationSlider = new javax.swing.JSlider();
        mutationLabel = new javax.swing.JLabel();
        mutationSlider = new javax.swing.JSlider();
        generationsValueLabel = new javax.swing.JLabel();
        populationValueLabel = new javax.swing.JLabel();
        mutationValueLabel = new javax.swing.JLabel();
        saveGaButton = new javax.swing.JButton();
        gaNameField = new javax.swing.JTextField();
        sideTabbedPane = new javax.swing.JTabbedPane();
        fitnessFunctionPanel = new javax.swing.JPanel();
        roadsSlider = new javax.swing.JSlider();
        roadsLabel = new javax.swing.JLabel();
        grassParksSlider = new javax.swing.JSlider();
        grassParksLabel = new javax.swing.JLabel();
        lightResidentialSlider = new javax.swing.JSlider();
        lightResidentialLabel = new javax.swing.JLabel();
        denseCommercialSlider = new javax.swing.JSlider();
        denseCommercialLabel = new javax.swing.JLabel();
        farmlandSlider = new javax.swing.JSlider();
        farmlandLabel = new javax.swing.JLabel();
        denseResidentialSlider = new javax.swing.JSlider();
        denseResidentialLabel = new javax.swing.JLabel();
        lightCommercialSider = new javax.swing.JSlider();
        lightCommercialLabel = new javax.swing.JLabel();
        industrySlider = new javax.swing.JSlider();
        industryLabel = new javax.swing.JLabel();
        hospitalSlider = new javax.swing.JSlider();
        policeSlider = new javax.swing.JSlider();
        fireSlider = new javax.swing.JSlider();
        educationSlider = new javax.swing.JSlider();
        hospitalLabel = new javax.swing.JLabel();
        policeLabel = new javax.swing.JLabel();
        fireLabel = new javax.swing.JLabel();
        educationLabel = new javax.swing.JLabel();
        resetFitnessFunctionButton = new javax.swing.JButton();
        statsPanel = new javax.swing.JPanel();
        roadsCostLabel = new javax.swing.JLabel();
        costLabel = new javax.swing.JLabel();
        grassParksCostLabel = new javax.swing.JLabel();
        lightResidentialCostLabel = new javax.swing.JLabel();
        DenseResidentialCostLabel = new javax.swing.JLabel();
        lightCommercialCostLabel = new javax.swing.JLabel();
        denseCommericalCostLabel = new javax.swing.JLabel();
        farmlandCostLabel = new javax.swing.JLabel();
        industryCostLabel = new javax.swing.JLabel();
        hosptialCostLabel = new javax.swing.JLabel();
        policeCostLabel = new javax.swing.JLabel();
        fireCostLabel = new javax.swing.JLabel();
        educationCostLabel = new javax.swing.JLabel();
        totalCostLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        utilityLabel = new javax.swing.JLabel();
        roadsUtilityLabel = new javax.swing.JLabel();
        GrassParksUtilityLabel = new javax.swing.JLabel();
        lightResidentialUtilityLabel = new javax.swing.JLabel();
        denseResidentialUtilityLabel = new javax.swing.JLabel();
        lightCommercialUtilityLabel = new javax.swing.JLabel();
        denseCommericalUtilityLabel = new javax.swing.JLabel();
        farmlandUtilityLabel = new javax.swing.JLabel();
        industryUtilityLabel = new javax.swing.JLabel();
        hospitalUtilityLabel = new javax.swing.JLabel();
        policeUtilityLabel = new javax.swing.JLabel();
        fireUtilityLabel = new javax.swing.JLabel();
        educationUtilityLabel = new javax.swing.JLabel();
        totalUtilityLabel = new javax.swing.JLabel();
        blockKeyPanel = new javax.swing.JPanel();
        roadsKeyLabel = new javax.swing.JLabel();
        grassParksKeyLabel = new javax.swing.JLabel();
        lightResidentialKeyLabel = new javax.swing.JLabel();
        denseCommercialKeyLabel = new javax.swing.JLabel();
        denseResidentialKeyLabel = new javax.swing.JLabel();
        lightCommercialKeyLabel = new javax.swing.JLabel();
        industryKeyLabel = new javax.swing.JLabel();
        hospitalKeyLabel = new javax.swing.JLabel();
        policeKeyLabel = new javax.swing.JLabel();
        fireKeyLabel = new javax.swing.JLabel();
        roadsKeyPanel = new javax.swing.JPanel();
        grassParksKeyPanel = new javax.swing.JPanel();
        lightResidentialKeyPanel = new javax.swing.JPanel();
        desneResidentialKeyPanel = new javax.swing.JPanel();
        lightCommercialKeyPanel = new javax.swing.JPanel();
        denseCommercialKeyPanel = new javax.swing.JPanel();
        industryKeyPanel = new javax.swing.JPanel();
        hospitalKeyPanel = new javax.swing.JPanel();
        policeKeyPanel = new javax.swing.JPanel();
        fireKeyPanel = new javax.swing.JPanel();
        educationKeyLabel = new javax.swing.JLabel();
        educationKeyPanel = new javax.swing.JPanel();
        waterKeyLabel = new javax.swing.JLabel();
        immovableObjectKeyLabel = new javax.swing.JLabel();
        waterKeyPanel = new javax.swing.JPanel();
        immovableObjectKeyPanel = new javax.swing.JPanel();
        farmlandKeyLabel = new javax.swing.JLabel();
        farmlandKeyPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fileManagerPane = new javax.swing.JTabbedPane();
        savedMapsPanel = new javax.swing.JPanel();
        savedMapsPane = new javax.swing.JScrollPane();
        savedMapsList = new javax.swing.JList<>();
        loadSavedMapButton = new javax.swing.JButton();
        deleteSavedMapButton = new javax.swing.JButton();
        searchSessionsPanel = new javax.swing.JPanel();
        searchSessionsPane = new javax.swing.JScrollPane();
        searchSessionsList = new javax.swing.JList<>();
        loadSearchSessionsButton = new javax.swing.JButton();
        deleteSearchSessionsButton = new javax.swing.JButton();
        populationMapsPanel = new javax.swing.JPanel();
        viewMapButton = new javax.swing.JButton();
        populationMapsPane = new javax.swing.JScrollPane();
        populationMapsList = new javax.swing.JList<>();
        savePopulationMapButton = new javax.swing.JButton();
        populationMapNameField = new javax.swing.JTextField();
        messagesPane = new javax.swing.JScrollPane();
        messagesOutputArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("City Evolver");
        setLocation(new java.awt.Point(0, 0));
        setName("cityEvolverFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        gaMenuPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        startGaButton.setText("Start");

        stopGaButton.setText("Stop");
        stopGaButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                stopGaButtonActionPerformed(evt);
            }
        });

        resetGaButton.setText("Reset");
        resetGaButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                resetGaButtonActionPerformed(evt);
            }
        });

        generationsSlider.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                generationsSliderStateChanged(evt);
            }
        });

        generationsLabel.setText("Generations");

        populationLabel.setText("Population");

        mutationLabel.setText("Mutation");

        generationsValueLabel.setText("150");

        populationValueLabel.setText("150");

        mutationValueLabel.setText("150");

        saveGaButton.setText("Save");

        javax.swing.GroupLayout gaMenuPanelLayout = new javax.swing.GroupLayout(gaMenuPanel);
        gaMenuPanel.setLayout(gaMenuPanelLayout);
        gaMenuPanelLayout.setHorizontalGroup(
            gaMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gaMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gaMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gaMenuPanelLayout.createSequentialGroup()
                        .addGroup(gaMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gaMenuPanelLayout.createSequentialGroup()
                                .addComponent(generationsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generationsSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(generationsValueLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(gaMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mutationValueLabel)
                            .addComponent(mutationLabel)))
                    .addGroup(gaMenuPanelLayout.createSequentialGroup()
                        .addGroup(gaMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gaMenuPanelLayout.createSequentialGroup()
                                .addComponent(populationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(populationSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(populationValueLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(gaMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startGaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveGaButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gaMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mutationSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(gaMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(gaNameField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, gaMenuPanelLayout.createSequentialGroup()
                            .addComponent(stopGaButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(resetGaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        gaMenuPanelLayout.setVerticalGroup(
            gaMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gaMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gaMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(generationsSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generationsLabel)
                    .addComponent(mutationSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mutationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gaMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generationsValueLabel)
                    .addComponent(mutationValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(gaMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gaMenuPanelLayout.createSequentialGroup()
                        .addGroup(gaMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(populationLabel)
                            .addComponent(populationSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(populationValueLabel))
                    .addGroup(gaMenuPanelLayout.createSequentialGroup()
                        .addGroup(gaMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startGaButton)
                            .addComponent(stopGaButton)
                            .addComponent(resetGaButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(gaMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveGaButton)
                            .addComponent(gaNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(64, 64, 64))
        );

        sideTabbedPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        roadsLabel.setText("Roads: 50");

        grassParksLabel.setText("Grass/Parks: 50");

        lightResidentialLabel.setText("LightResidential: 50");

        denseCommercialLabel.setText("DenseCommercial: 50");

        farmlandLabel.setText("Farmland: 50");

        denseResidentialLabel.setText("DenseResidential: 50");

        lightCommercialLabel.setText("LightCommercial: 50");

        industryLabel.setText("Industry: 50");

        hospitalLabel.setText("Hospital: 50");

        policeLabel.setText("Police: 50");

        fireLabel.setText("Fire: 50");

        educationLabel.setText("Education: 50");

        resetFitnessFunctionButton.setText("Reset");
        resetFitnessFunctionButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                resetFitnessFunctionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fitnessFunctionPanelLayout = new javax.swing.GroupLayout(fitnessFunctionPanel);
        fitnessFunctionPanel.setLayout(fitnessFunctionPanelLayout);
        fitnessFunctionPanelLayout.setHorizontalGroup(
            fitnessFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fitnessFunctionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fitnessFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fitnessFunctionPanelLayout.createSequentialGroup()
                        .addComponent(industrySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(industryLabel))
                    .addGroup(fitnessFunctionPanelLayout.createSequentialGroup()
                        .addGroup(fitnessFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(denseResidentialSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(farmlandSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(denseCommercialSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lightResidentialSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(grassParksSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(roadsSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fitnessFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(denseResidentialLabel)
                            .addComponent(grassParksLabel)
                            .addComponent(roadsLabel)
                            .addComponent(lightResidentialLabel)
                            .addComponent(denseCommercialLabel)
                            .addComponent(farmlandLabel)))
                    .addGroup(fitnessFunctionPanelLayout.createSequentialGroup()
                        .addComponent(lightCommercialSider, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lightCommercialLabel))
                    .addGroup(fitnessFunctionPanelLayout.createSequentialGroup()
                        .addComponent(hospitalSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hospitalLabel))
                    .addGroup(fitnessFunctionPanelLayout.createSequentialGroup()
                        .addComponent(policeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(policeLabel))
                    .addGroup(fitnessFunctionPanelLayout.createSequentialGroup()
                        .addComponent(fireSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fireLabel))
                    .addGroup(fitnessFunctionPanelLayout.createSequentialGroup()
                        .addComponent(educationSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(educationLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(fitnessFunctionPanelLayout.createSequentialGroup()
                .addComponent(resetFitnessFunctionButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        fitnessFunctionPanelLayout.setVerticalGroup(
            fitnessFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fitnessFunctionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fitnessFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(roadsSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roadsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fitnessFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(grassParksSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grassParksLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fitnessFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lightResidentialSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lightResidentialLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fitnessFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(denseResidentialSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(denseResidentialLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fitnessFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lightCommercialSider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lightCommercialLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fitnessFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(denseCommercialSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(denseCommercialLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fitnessFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(farmlandSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(farmlandLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fitnessFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(industrySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(industryLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fitnessFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hospitalSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hospitalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fitnessFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(policeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(policeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fitnessFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fireSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fireLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fitnessFunctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(educationSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(educationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetFitnessFunctionButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sideTabbedPane.addTab("Fitness Function", fitnessFunctionPanel);

        statsPanel.setName(""); // NOI18N

        roadsCostLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        roadsCostLabel.setText("Roads: 50");

        costLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        costLabel.setText("Cost");

        grassParksCostLabel.setText("Grass/Parks: 50");

        lightResidentialCostLabel.setText("LightResidential: 50");

        DenseResidentialCostLabel.setText("DenseResidential: 50");

        lightCommercialCostLabel.setText("LightCommercial: 50");

        denseCommericalCostLabel.setText("DenseCommercial: 50");

        farmlandCostLabel.setText("Farmland: 50");

        industryCostLabel.setText("Industry: 50");

        hosptialCostLabel.setText("Hospital: 50");

        policeCostLabel.setText("Police: 50");

        fireCostLabel.setText("Fire: 50");

        educationCostLabel.setText("Education: 50");

        totalCostLabel.setText("Total: 2000");

        javax.swing.GroupLayout statsPanelLayout = new javax.swing.GroupLayout(statsPanel);
        statsPanel.setLayout(statsPanelLayout);
        statsPanelLayout.setHorizontalGroup(
            statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roadsCostLabel)
                    .addComponent(industryCostLabel)
                    .addComponent(DenseResidentialCostLabel)
                    .addComponent(grassParksCostLabel)
                    .addComponent(lightResidentialCostLabel)
                    .addComponent(denseCommericalCostLabel)
                    .addComponent(farmlandCostLabel)
                    .addComponent(lightCommercialCostLabel)
                    .addComponent(hosptialCostLabel)
                    .addComponent(policeCostLabel)
                    .addComponent(fireCostLabel)
                    .addComponent(educationCostLabel)
                    .addComponent(totalCostLabel)
                    .addComponent(costLabel))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        statsPanelLayout.setVerticalGroup(
            statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(costLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roadsCostLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grassParksCostLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lightResidentialCostLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DenseResidentialCostLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lightCommercialCostLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(denseCommericalCostLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(farmlandCostLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(industryCostLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hosptialCostLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(policeCostLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fireCostLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(educationCostLabel)
                .addGap(18, 18, 18)
                .addComponent(totalCostLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sideTabbedPane.addTab("Cost", statsPanel);

        utilityLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        utilityLabel.setText("Utility");

        roadsUtilityLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        roadsUtilityLabel.setText("Roads: 50 meters of road");

        GrassParksUtilityLabel.setText("Grass/Parks: 50 m^3 of green space");

        lightResidentialUtilityLabel.setText("LightResidential: 50 population");

        denseResidentialUtilityLabel.setText("DenseResidential: 50 population");

        lightCommercialUtilityLabel.setText("LightCommercial: 50 jobs");

        denseCommericalUtilityLabel.setText("DenseCommercial: 50 jobs");

        farmlandUtilityLabel.setText("Farmland: 50 servings");

        industryUtilityLabel.setText("Industry: 50 jobs");

        hospitalUtilityLabel.setText("Hospital: 50 servings");

        policeUtilityLabel.setText("Police: 50 servings");

        fireUtilityLabel.setText("Fire: 50 servings");

        educationUtilityLabel.setText("Education: 50 servings");

        totalUtilityLabel.setText("Total: 2000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roadsUtilityLabel)
                    .addComponent(industryUtilityLabel)
                    .addComponent(denseResidentialUtilityLabel)
                    .addComponent(GrassParksUtilityLabel)
                    .addComponent(lightResidentialUtilityLabel)
                    .addComponent(denseCommericalUtilityLabel)
                    .addComponent(farmlandUtilityLabel)
                    .addComponent(lightCommercialUtilityLabel)
                    .addComponent(hospitalUtilityLabel)
                    .addComponent(policeUtilityLabel)
                    .addComponent(fireUtilityLabel)
                    .addComponent(educationUtilityLabel)
                    .addComponent(totalUtilityLabel)
                    .addComponent(utilityLabel))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(utilityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roadsUtilityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GrassParksUtilityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lightResidentialUtilityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(denseResidentialUtilityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lightCommercialUtilityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(denseCommericalUtilityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(farmlandUtilityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(industryUtilityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hospitalUtilityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(policeUtilityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fireUtilityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(educationUtilityLabel)
                .addGap(18, 18, 18)
                .addComponent(totalUtilityLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sideTabbedPane.addTab("Utility", jPanel1);

        roadsKeyLabel.setText("Roads");

        grassParksKeyLabel.setText("Grass/Parks");

        lightResidentialKeyLabel.setText("LightResidential");

        denseCommercialKeyLabel.setText("DenseCommercial");

        denseResidentialKeyLabel.setText("DenseResidential");

        lightCommercialKeyLabel.setText("LightCommercial");

        industryKeyLabel.setText("Industry");

        hospitalKeyLabel.setText("Hospital");

        policeKeyLabel.setText("Police");

        fireKeyLabel.setText("Fire");

        roadsKeyPanel.setBackground(new java.awt.Color(128, 128, 128));

        javax.swing.GroupLayout roadsKeyPanelLayout = new javax.swing.GroupLayout(roadsKeyPanel);
        roadsKeyPanel.setLayout(roadsKeyPanelLayout);
        roadsKeyPanelLayout.setHorizontalGroup(
            roadsKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );
        roadsKeyPanelLayout.setVerticalGroup(
            roadsKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        grassParksKeyPanel.setBackground(new java.awt.Color(16, 209, 0));

        javax.swing.GroupLayout grassParksKeyPanelLayout = new javax.swing.GroupLayout(grassParksKeyPanel);
        grassParksKeyPanel.setLayout(grassParksKeyPanelLayout);
        grassParksKeyPanelLayout.setHorizontalGroup(
            grassParksKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        grassParksKeyPanelLayout.setVerticalGroup(
            grassParksKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lightResidentialKeyPanel.setBackground(new java.awt.Color(0, 255, 200));

        javax.swing.GroupLayout lightResidentialKeyPanelLayout = new javax.swing.GroupLayout(lightResidentialKeyPanel);
        lightResidentialKeyPanel.setLayout(lightResidentialKeyPanelLayout);
        lightResidentialKeyPanelLayout.setHorizontalGroup(
            lightResidentialKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lightResidentialKeyPanelLayout.setVerticalGroup(
            lightResidentialKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desneResidentialKeyPanel.setBackground(new java.awt.Color(0, 100, 0));

        javax.swing.GroupLayout desneResidentialKeyPanelLayout = new javax.swing.GroupLayout(desneResidentialKeyPanel);
        desneResidentialKeyPanel.setLayout(desneResidentialKeyPanelLayout);
        desneResidentialKeyPanelLayout.setHorizontalGroup(
            desneResidentialKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desneResidentialKeyPanelLayout.setVerticalGroup(
            desneResidentialKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lightCommercialKeyPanel.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout lightCommercialKeyPanelLayout = new javax.swing.GroupLayout(lightCommercialKeyPanel);
        lightCommercialKeyPanel.setLayout(lightCommercialKeyPanelLayout);
        lightCommercialKeyPanelLayout.setHorizontalGroup(
            lightCommercialKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lightCommercialKeyPanelLayout.setVerticalGroup(
            lightCommercialKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        denseCommercialKeyPanel.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout denseCommercialKeyPanelLayout = new javax.swing.GroupLayout(denseCommercialKeyPanel);
        denseCommercialKeyPanel.setLayout(denseCommercialKeyPanelLayout);
        denseCommercialKeyPanelLayout.setHorizontalGroup(
            denseCommercialKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        denseCommercialKeyPanelLayout.setVerticalGroup(
            denseCommercialKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        industryKeyPanel.setBackground(new java.awt.Color(255, 201, 0));

        javax.swing.GroupLayout industryKeyPanelLayout = new javax.swing.GroupLayout(industryKeyPanel);
        industryKeyPanel.setLayout(industryKeyPanelLayout);
        industryKeyPanelLayout.setHorizontalGroup(
            industryKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        industryKeyPanelLayout.setVerticalGroup(
            industryKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        hospitalKeyPanel.setBackground(new java.awt.Color(250, 250, 250));

        javax.swing.GroupLayout hospitalKeyPanelLayout = new javax.swing.GroupLayout(hospitalKeyPanel);
        hospitalKeyPanel.setLayout(hospitalKeyPanelLayout);
        hospitalKeyPanelLayout.setHorizontalGroup(
            hospitalKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hospitalKeyPanelLayout.setVerticalGroup(
            hospitalKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        policeKeyPanel.setBackground(new java.awt.Color(191, 95, 255));

        javax.swing.GroupLayout policeKeyPanelLayout = new javax.swing.GroupLayout(policeKeyPanel);
        policeKeyPanel.setLayout(policeKeyPanelLayout);
        policeKeyPanelLayout.setHorizontalGroup(
            policeKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        policeKeyPanelLayout.setVerticalGroup(
            policeKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        fireKeyPanel.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout fireKeyPanelLayout = new javax.swing.GroupLayout(fireKeyPanel);
        fireKeyPanel.setLayout(fireKeyPanelLayout);
        fireKeyPanelLayout.setHorizontalGroup(
            fireKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        fireKeyPanelLayout.setVerticalGroup(
            fireKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        educationKeyLabel.setText("Education");

        educationKeyPanel.setBackground(new java.awt.Color(101, 67, 33));

        javax.swing.GroupLayout educationKeyPanelLayout = new javax.swing.GroupLayout(educationKeyPanel);
        educationKeyPanel.setLayout(educationKeyPanelLayout);
        educationKeyPanelLayout.setHorizontalGroup(
            educationKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        educationKeyPanelLayout.setVerticalGroup(
            educationKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        waterKeyLabel.setText("Water");

        immovableObjectKeyLabel.setText("ImmovableObject");

        waterKeyPanel.setBackground(new java.awt.Color(0, 193, 238));

        javax.swing.GroupLayout waterKeyPanelLayout = new javax.swing.GroupLayout(waterKeyPanel);
        waterKeyPanel.setLayout(waterKeyPanelLayout);
        waterKeyPanelLayout.setHorizontalGroup(
            waterKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        waterKeyPanelLayout.setVerticalGroup(
            waterKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        immovableObjectKeyPanel.setBackground(new java.awt.Color(16, 16, 16));

        javax.swing.GroupLayout immovableObjectKeyPanelLayout = new javax.swing.GroupLayout(immovableObjectKeyPanel);
        immovableObjectKeyPanel.setLayout(immovableObjectKeyPanelLayout);
        immovableObjectKeyPanelLayout.setHorizontalGroup(
            immovableObjectKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        immovableObjectKeyPanelLayout.setVerticalGroup(
            immovableObjectKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        farmlandKeyLabel.setText("Farmland");

        farmlandKeyPanel.setBackground(new java.awt.Color(255, 236, 139));

        javax.swing.GroupLayout farmlandKeyPanelLayout = new javax.swing.GroupLayout(farmlandKeyPanel);
        farmlandKeyPanel.setLayout(farmlandKeyPanelLayout);
        farmlandKeyPanelLayout.setHorizontalGroup(
            farmlandKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        farmlandKeyPanelLayout.setVerticalGroup(
            farmlandKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        jLabel1.setText("Block Key");

        javax.swing.GroupLayout blockKeyPanelLayout = new javax.swing.GroupLayout(blockKeyPanel);
        blockKeyPanel.setLayout(blockKeyPanelLayout);
        blockKeyPanelLayout.setHorizontalGroup(
            blockKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockKeyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(blockKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(blockKeyPanelLayout.createSequentialGroup()
                        .addGroup(blockKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(roadsKeyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(grassParksKeyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lightResidentialKeyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(desneResidentialKeyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lightCommercialKeyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(denseCommercialKeyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(industryKeyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hospitalKeyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(policeKeyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fireKeyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(educationKeyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(waterKeyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(immovableObjectKeyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(farmlandKeyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(blockKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(immovableObjectKeyLabel)
                            .addComponent(waterKeyLabel)
                            .addComponent(educationKeyLabel)
                            .addComponent(grassParksKeyLabel)
                            .addComponent(roadsKeyLabel)
                            .addComponent(lightResidentialKeyLabel)
                            .addComponent(denseCommercialKeyLabel)
                            .addComponent(denseResidentialKeyLabel)
                            .addComponent(industryKeyLabel)
                            .addComponent(hospitalKeyLabel)
                            .addComponent(policeKeyLabel)
                            .addComponent(lightCommercialKeyLabel)
                            .addComponent(fireKeyLabel)
                            .addComponent(farmlandKeyLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(blockKeyPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        blockKeyPanelLayout.setVerticalGroup(
            blockKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blockKeyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(blockKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roadsKeyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roadsKeyLabel))
                .addGap(10, 10, 10)
                .addGroup(blockKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(grassParksKeyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(grassParksKeyLabel))
                .addGap(10, 10, 10)
                .addGroup(blockKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lightResidentialKeyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lightResidentialKeyLabel))
                .addGap(10, 10, 10)
                .addGroup(blockKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(desneResidentialKeyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(denseResidentialKeyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(blockKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lightCommercialKeyLabel)
                    .addComponent(lightCommercialKeyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(blockKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(denseCommercialKeyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(denseCommercialKeyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(blockKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(farmlandKeyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(farmlandKeyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(blockKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(industryKeyLabel)
                    .addComponent(industryKeyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(blockKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hospitalKeyLabel)
                    .addComponent(hospitalKeyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(blockKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(policeKeyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(policeKeyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(blockKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fireKeyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fireKeyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(blockKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(educationKeyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(educationKeyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(blockKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(waterKeyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waterKeyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(blockKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(immovableObjectKeyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(immovableObjectKeyLabel))
                .addContainerGap())
        );

        sideTabbedPane.addTab("Key", blockKeyPanel);

        fileManagerPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        savedMapsList.setModel(new javax.swing.AbstractListModel<String>()
        {
            String[] strings = { "World 1", "World 2", "Test" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        savedMapsPane.setViewportView(savedMapsList);

        loadSavedMapButton.setText("Load");
        loadSavedMapButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                loadSavedMapButtonActionPerformed(evt);
            }
        });

        deleteSavedMapButton.setText("Delete");

        javax.swing.GroupLayout savedMapsPanelLayout = new javax.swing.GroupLayout(savedMapsPanel);
        savedMapsPanel.setLayout(savedMapsPanelLayout);
        savedMapsPanelLayout.setHorizontalGroup(
            savedMapsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savedMapsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(savedMapsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(savedMapsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loadSavedMapButton)
                    .addComponent(deleteSavedMapButton))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        savedMapsPanelLayout.setVerticalGroup(
            savedMapsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(savedMapsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(savedMapsPanelLayout.createSequentialGroup()
                .addComponent(loadSavedMapButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteSavedMapButton)
                .addContainerGap())
        );

        fileManagerPane.addTab("Saved Maps", savedMapsPanel);

        searchSessionsList.setModel(new javax.swing.AbstractListModel<String>()
        {
            String[] strings = { "World 1", "World 2", "Test" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        searchSessionsPane.setViewportView(searchSessionsList);

        loadSearchSessionsButton.setText("Load");

        deleteSearchSessionsButton.setText("Delete");

        javax.swing.GroupLayout searchSessionsPanelLayout = new javax.swing.GroupLayout(searchSessionsPanel);
        searchSessionsPanel.setLayout(searchSessionsPanelLayout);
        searchSessionsPanelLayout.setHorizontalGroup(
            searchSessionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchSessionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchSessionsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchSessionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loadSearchSessionsButton)
                    .addComponent(deleteSearchSessionsButton))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        searchSessionsPanelLayout.setVerticalGroup(
            searchSessionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchSessionsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(searchSessionsPanelLayout.createSequentialGroup()
                .addComponent(loadSearchSessionsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(deleteSearchSessionsButton)
                .addContainerGap())
        );

        fileManagerPane.addTab("Search Sessions", searchSessionsPanel);

        viewMapButton.setText("View");

        populationMapsList.setModel(new javax.swing.AbstractListModel<String>()
        {
            String[] strings = { "World 1", "World 2", "Test" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        populationMapsPane.setViewportView(populationMapsList);

        savePopulationMapButton.setText("Save");

        javax.swing.GroupLayout populationMapsPanelLayout = new javax.swing.GroupLayout(populationMapsPanel);
        populationMapsPanel.setLayout(populationMapsPanelLayout);
        populationMapsPanelLayout.setHorizontalGroup(
            populationMapsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, populationMapsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(populationMapsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(populationMapsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(populationMapsPanelLayout.createSequentialGroup()
                        .addComponent(viewMapButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(populationMapsPanelLayout.createSequentialGroup()
                        .addComponent(savePopulationMapButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(populationMapNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)))
                .addContainerGap())
        );
        populationMapsPanelLayout.setVerticalGroup(
            populationMapsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(populationMapsPanelLayout.createSequentialGroup()
                .addComponent(viewMapButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(populationMapsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savePopulationMapButton)
                    .addComponent(populationMapNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(populationMapsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        fileManagerPane.addTab("Population Maps", populationMapsPanel);

        messagesOutputArea.setEditable(false);
        messagesOutputArea.setColumns(20);
        messagesOutputArea.setRows(5);
        messagesPane.setViewportView(messagesOutputArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topSeperator)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sideTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fileManagerPane, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(messagesPane)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gaMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gaMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileManagerPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messagesPane))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(topSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sideTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopGaButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_stopGaButtonActionPerformed
    {//GEN-HEADEREND:event_stopGaButtonActionPerformed

    }//GEN-LAST:event_stopGaButtonActionPerformed

    private void resetGaButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_resetGaButtonActionPerformed
    {//GEN-HEADEREND:event_resetGaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetGaButtonActionPerformed

    private void resetFitnessFunctionButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_resetFitnessFunctionButtonActionPerformed
    {//GEN-HEADEREND:event_resetFitnessFunctionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetFitnessFunctionButtonActionPerformed

    private void loadSavedMapButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_loadSavedMapButtonActionPerformed
    {//GEN-HEADEREND:event_loadSavedMapButtonActionPerformed
        if(openGLInstance != null && openGLInstance.isAlive())
        {
            renderer.setRunning(false);
            try
            {
                openGLInstance.join();
            } catch (InterruptedException ex)
            {
                Logger.getLogger(GUIForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        

        renderer.setRunning(true);
//        renderer.viewMap(individual);
        openGLInstance = new Thread(renderer);
        openGLInstance.start();
    }//GEN-LAST:event_loadSavedMapButtonActionPerformed

    private void generationsSliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_generationsSliderStateChanged
    {//GEN-HEADEREND:event_generationsSliderStateChanged
        int value = generationsSlider.getValue();
        if (generationsSlider.getMaximum() == generationsSlider.getValue())
        {
            value = Integer.MAX_VALUE;
        }
        else if (generationsSlider.getMinimum() == generationsSlider.getValue())
        {
            value = 1;
        }
        else
        {
            value =  generationsSlider.getValue() * 500; 
        }
        if (value == Integer.MAX_VALUE)
        {
            generationsValueLabel.setText("Infinity");
        }
        else
        {
            generationsValueLabel.setText(Integer.toString(value));
        }
    }//GEN-LAST:event_generationsSliderStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new GUIForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DenseResidentialCostLabel;
    private javax.swing.JLabel GrassParksUtilityLabel;
    private javax.swing.JPanel blockKeyPanel;
    private javax.swing.JLabel costLabel;
    private javax.swing.JButton deleteSavedMapButton;
    private javax.swing.JButton deleteSearchSessionsButton;
    private javax.swing.JLabel denseCommercialKeyLabel;
    private javax.swing.JPanel denseCommercialKeyPanel;
    private javax.swing.JLabel denseCommercialLabel;
    private javax.swing.JSlider denseCommercialSlider;
    private javax.swing.JLabel denseCommericalCostLabel;
    private javax.swing.JLabel denseCommericalUtilityLabel;
    private javax.swing.JLabel denseResidentialKeyLabel;
    private javax.swing.JLabel denseResidentialLabel;
    private javax.swing.JSlider denseResidentialSlider;
    private javax.swing.JLabel denseResidentialUtilityLabel;
    private javax.swing.JPanel desneResidentialKeyPanel;
    private javax.swing.JLabel educationCostLabel;
    private javax.swing.JLabel educationKeyLabel;
    private javax.swing.JPanel educationKeyPanel;
    private javax.swing.JLabel educationLabel;
    private javax.swing.JSlider educationSlider;
    private javax.swing.JLabel educationUtilityLabel;
    private javax.swing.JLabel farmlandCostLabel;
    private javax.swing.JLabel farmlandKeyLabel;
    private javax.swing.JPanel farmlandKeyPanel;
    private javax.swing.JLabel farmlandLabel;
    private javax.swing.JSlider farmlandSlider;
    private javax.swing.JLabel farmlandUtilityLabel;
    private javax.swing.JTabbedPane fileManagerPane;
    private javax.swing.JLabel fireCostLabel;
    private javax.swing.JLabel fireKeyLabel;
    private javax.swing.JPanel fireKeyPanel;
    private javax.swing.JLabel fireLabel;
    private javax.swing.JSlider fireSlider;
    private javax.swing.JLabel fireUtilityLabel;
    private javax.swing.JPanel fitnessFunctionPanel;
    private javax.swing.JPanel gaMenuPanel;
    private javax.swing.JTextField gaNameField;
    private javax.swing.JLabel generationsLabel;
    private javax.swing.JSlider generationsSlider;
    private javax.swing.JLabel generationsValueLabel;
    private javax.swing.JLabel grassParksCostLabel;
    private javax.swing.JLabel grassParksKeyLabel;
    private javax.swing.JPanel grassParksKeyPanel;
    private javax.swing.JLabel grassParksLabel;
    private javax.swing.JSlider grassParksSlider;
    private javax.swing.JLabel hospitalKeyLabel;
    private javax.swing.JPanel hospitalKeyPanel;
    private javax.swing.JLabel hospitalLabel;
    private javax.swing.JSlider hospitalSlider;
    private javax.swing.JLabel hospitalUtilityLabel;
    private javax.swing.JLabel hosptialCostLabel;
    private javax.swing.JLabel immovableObjectKeyLabel;
    private javax.swing.JPanel immovableObjectKeyPanel;
    private javax.swing.JLabel industryCostLabel;
    private javax.swing.JLabel industryKeyLabel;
    private javax.swing.JPanel industryKeyPanel;
    private javax.swing.JLabel industryLabel;
    private javax.swing.JSlider industrySlider;
    private javax.swing.JLabel industryUtilityLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lightCommercialCostLabel;
    private javax.swing.JLabel lightCommercialKeyLabel;
    private javax.swing.JPanel lightCommercialKeyPanel;
    private javax.swing.JLabel lightCommercialLabel;
    private javax.swing.JSlider lightCommercialSider;
    private javax.swing.JLabel lightCommercialUtilityLabel;
    private javax.swing.JLabel lightResidentialCostLabel;
    private javax.swing.JLabel lightResidentialKeyLabel;
    private javax.swing.JPanel lightResidentialKeyPanel;
    private javax.swing.JLabel lightResidentialLabel;
    private javax.swing.JSlider lightResidentialSlider;
    private javax.swing.JLabel lightResidentialUtilityLabel;
    private javax.swing.JButton loadSavedMapButton;
    private javax.swing.JButton loadSearchSessionsButton;
    private javax.swing.JTextArea messagesOutputArea;
    private javax.swing.JScrollPane messagesPane;
    private javax.swing.JLabel mutationLabel;
    private javax.swing.JSlider mutationSlider;
    private javax.swing.JLabel mutationValueLabel;
    private javax.swing.JLabel policeCostLabel;
    private javax.swing.JLabel policeKeyLabel;
    private javax.swing.JPanel policeKeyPanel;
    private javax.swing.JLabel policeLabel;
    private javax.swing.JSlider policeSlider;
    private javax.swing.JLabel policeUtilityLabel;
    private javax.swing.JLabel populationLabel;
    private javax.swing.JTextField populationMapNameField;
    private javax.swing.JList<String> populationMapsList;
    private javax.swing.JScrollPane populationMapsPane;
    private javax.swing.JPanel populationMapsPanel;
    private javax.swing.JSlider populationSlider;
    private javax.swing.JLabel populationValueLabel;
    private javax.swing.JButton resetFitnessFunctionButton;
    private javax.swing.JButton resetGaButton;
    private javax.swing.JLabel roadsCostLabel;
    private javax.swing.JLabel roadsKeyLabel;
    private javax.swing.JPanel roadsKeyPanel;
    private javax.swing.JLabel roadsLabel;
    private javax.swing.JSlider roadsSlider;
    private javax.swing.JLabel roadsUtilityLabel;
    private javax.swing.JButton saveGaButton;
    private javax.swing.JButton savePopulationMapButton;
    private javax.swing.JList<String> savedMapsList;
    private javax.swing.JScrollPane savedMapsPane;
    private javax.swing.JPanel savedMapsPanel;
    private javax.swing.JList<String> searchSessionsList;
    private javax.swing.JScrollPane searchSessionsPane;
    private javax.swing.JPanel searchSessionsPanel;
    private javax.swing.JTabbedPane sideTabbedPane;
    private javax.swing.JButton startGaButton;
    private javax.swing.JPanel statsPanel;
    private javax.swing.JButton stopGaButton;
    private javax.swing.JSeparator topSeperator;
    private javax.swing.JLabel totalCostLabel;
    private javax.swing.JLabel totalUtilityLabel;
    private javax.swing.JLabel utilityLabel;
    private javax.swing.JButton viewMapButton;
    private javax.swing.JLabel waterKeyLabel;
    private javax.swing.JPanel waterKeyPanel;
    // End of variables declaration//GEN-END:variables
}
